{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data: 
  {{- range $name, $config := .Values.configmap.values }}
  {{ $name }}: {{ $config | quote }}
  {{- end }}
{{- end }}