{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: {{ .Values.secrets.type }}
data:
  {{- range $name, $config := .Values.secrets.values }}
  {{ $name }}: {{ $config | b64enc | quote  }}
  {{- end }}
{{- end }}